apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: akv-openhack
spec:
  provider: azure
  secretObjects:
  - secretName: akv-secrets
    type: Opaque
    data: 
    - objectName: SQL-USER
      key: SQL-USER
    - objectName: SQL-PASSWORD
      key: SQL-PASSWORD
    - objectName: SQL-SERVER
      key: SQL-SERVER
  parameters:
    keyvaultName: "akv-openhack-001"       # The name of the Azure Key Vault
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "478f0f24-3185-44ab-8ae2-c70c96b2c3fd" # The clientId of the addon-created managed identity
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: SQL-USER
          objectType: secret
        - |
          objectName: SQL-PASSWORD
          objectType: secret
        - |
          objectName: SQL-SERVER
          objectType: secret
    tenantId: "6042515d-a7d2-4756-a080-dc85bfaf95a4"               # the tenant ID containing the Azure Key Vault instance